# Generated by Django 5.1.7 on 2025-03-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_remove_tenantprofile_user_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='Customer Mobile Number', max_length=100, null=True),
        ),
    ]
