# Generated by Django 5.1.7 on 2025-03-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('MEN', 'MEN'), ('WOMEN', 'WOMEN'), ('TEEN', 'TEEN'), ('UNISEX', 'UNISEX')], default='MEN', max_length=100),
        ),
    ]
