# Generated by Django 5.1.7 on 2025-03-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_cartorder_cartorderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='pric',
            new_name='price',
        ),
    ]
